volumes:
  mongodb:
  
services:
  api:
    container_name: Project-x
    image: project-x
    restart: unless-stopped
    build:
      context: ./
    volumes:
      - .:/Project-x
      - /Project-x/node_modules
    ports:
      - 3001:3001
    networks:
      - projectX-network
    # depends_on:
    #   - postgres
    command: npx nest start --watch
  mongodb:
    image: mongo
    volumes:
      - mongodb:/data/db
    ports:
      - 27017:27017
    networks:
      - projectX-network
    restart: unless-stopped
    logging:
      driver: none
networks:
  projectX-network:
    external: true